### ISSUE TITLE
how update

### ISSUE THREAD

**Issue by wifi75** [OpenSprinkler/OpenSprinkler-Weather#106]
Hello my version installed it is 2.0.3, what is terminl command for update to latest version?

**Comment by wifi75** [comment]
Hello sorry but what are the steps to upgrade a raspberry?

**Comment by wifi75** [comment]
not work 
![image](https://user-images.githubusercontent.com/31816231/119843670-0cc7db00-bf08-11eb-8ccc-f278ab855569.png)

**Comment by salbahra** [comment]
Try:

git stash

Then:

git pull

**Comment by salbahra** [comment]
Please read your own screenshot and follow the directions.
