### ISSUE TITLE
Instllation on ubuntu

### ISSUE THREAD

**Issue by wifi75** [OpenSprinkler/OpenSprinkler-Weather#109]
Hello I want install weather service on ubuntu machine,
can Explane me how I can do it?

**Comment by salbahra** [comment]
Our documentation page which has instructions for Raspberry Pi will work for installing on Ubuntu as well. The only difference is step 1 where you can install node using your package manager.

Install Documentation: https://github.com/OpenSprinkler/OpenSprinkler-Weather/blob/master/docs/local-installation.md
