### ISSUE TITLE
soft rain sensor via weather service

### ISSUE THREAD

**Issue by beaverdude** [OpenSprinkler/OpenSprinkler-Weather#117]
https://github.com/OpenSprinkler/OpenSprinkler-Weather/blob/d1deef12490a18ad2de3869b673d1f88a295885c/routes/adjustmentMethods/EToAdjustmentMethod.ts#L24-L32

Will you consider enabling it since production weather service is working with darksky instead of owm?

**Comment by Pedrock** [comment]
@rayshobby May I ask why this was closed? 

I got an OpenSprinkler system recently and it's great but I have one issue with it, which is that it will sometimes water while it's raining. I can get a rain sensor, but it would be nice if I could avoid that by having this instead. And if it takes the forecast for the next few hours I think that's even better (assuming the forecast is reliable) as that would also prevent the system from watering right before it starts raining, which is something that's obviously not possible with a rain sensor.

Maybe this could be a separate configuration if you think some people might not want this for some reason?
If needed I can dedicate some time to implement it.
