### ISSUE TITLE
What do these .env parameters do?

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#118]
The usage of most .env parameters is described in the instructions for setting up a local weather servicer on a Raspberry Pi.  However, there are four parameters that are not described in any of the documentation.  I would like to know what they do and whether they can be used on a local weather server:

GOOGLE_MAPS_API_KEY
LOCAL_PERSISTENCE
PWS_WEATHER_PROVIDER
GEOCODER

Thanks,

Rog

**Comment by salbahra** [comment]
These variables were added when Weather Underground started closing up their API and work as follows:

`GEOCODER` defines which service will be used to convert a location name to coordinates. The available options are Google Maps and WUnderground. Google Maps uses `GOOGLE_MAPS_API_KEY` to authenticate with the API.

`PWS_WEATHER_PROVIDER` defines which weather service to use which can be: DarkSky, OpenWeatherMaps, WUnderground, or a local weather service. When using a local weather service, you can have the OpenSprinkler weather service cache the weather by setting `LOCAL_PERSISTENCE` to true.

We will try to update the documentation with this information ASAP.

Thank you,
Samer
