### ISSUE TITLE
How to turn on caching?

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#119]
Caching is used by the weather server that runs in the Amazon cloud to provide a consistent water level adjustment throughout the day.  Can I use that feature with a local weather server?  How do I turn it on?

[I need this to make ETo work correctly when sprinklers can't/don't run every day.]

Rog

**Comment by rayshobby** [comment]
shouldCacheWateringScale() is a function per weather service provider, you can define it for each weather service provider individually:
https://github.com/OpenSprinkler/OpenSprinkler-Weather/blob/master/routes/weatherProviders/Apple.ts#L179
