### ISSUE TITLE
Using OWM to trigger rain delay

### ISSUE THREAD

**Issue by PeteBa** [OpenSprinkler/OpenSprinkler-Weather#13]
Looks like OWM has a different way they flag "raining" weather conditions which is used by OS for Rain Delay.  Looking at the function `checkRainStatus( weather )`, I think the list of `adverseWords` needs to be "Thunderstorm", "Drizzle", "Rain", "Snow" and the check should be against the `weather.main` field returned by the api rather than the icon field. See this link [here](https://openweathermap.org/weather-conditions).

With the old WU stream, this function would have triggered a rain delay from actual historical rain. With OWM this would need a call to the "current" api but that would again double the api calls. An alternative could be to just use the first of the 3 hour forecasts. So logic would be if rain is predicted in the next 3 hours then trigger a rain delay ?

**Comment by salbahra** [comment]
Thank you for your fix in #16
