### ISSUE TITLE
Dark Sky being replaced by Apple WeatherKit

### ISSUE THREAD

**Issue by zaxbux** [OpenSprinkler/OpenSprinkler-Weather#130]
I wanted to give a heads up that the Dark Sky API will be shut down next year ([Blog Post](https://blog.darksky.net/)). It is being replaced by Apple WeatherKit. From the details that Apple has released so far, the [REST API](https://developer.apple.com/documentation/weatherkitrestapi) will require enrollment in the Apple Developer program.

**Comment by rmloeb** [comment]
Is the Apple Developer Program still $99/year?

**Comment by zaxbux** [comment]
Yes, or $119 CAD.

**Comment by rayshobby** [comment]
Thanks. Yes we are aware of this. We are already enrolled in the Apple Developer Program because we maintain and release iOS apps.
