### ISSUE TITLE
California rain restrictions should be 0.1" not 0.01"

### ISSUE THREAD

**Issue by shampeon** [OpenSprinkler/OpenSprinkler-Weather#14]
The manual states that the California rain restrictions should apply when 0.1" is recorded. In the code, however, it is 0.01". A hundredth of an inch of rain is typically an immeasurable amount of rain, and regardless is too little to trigger a pause of 48 hours. A tenth (0.1") is more reasonable.

Note that the 2018 California rain restrictions actually state that 0.25" of rain is the threshold, not 0.1" [1].

[1] https://www.sjwater.com/customer-care/help-information/drought-information

**Comment by shampeon** [comment]
Fix is in https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/15

**Comment by salbahra** [comment]
#15 is merged in now, thank you!
