### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by PipeDeveloper** [OpenSprinkler/OpenSprinkler-Weather#17]
I have bought an OpenSprinkler hat for my raspberry pi, how do i install this? i dont have much experience with js

**Comment by rayshobby** [comment]
The instructions are here:
https://openthings.freshdesk.com/support/solutions/articles/5000631599-installing-and-updating-the-unified-firmware
also, this is not a question for the weather script, so you are posting this question in the wrong repo.

**Comment by PipeDeveloper** [comment]
I thought it was like a pluging for the main firmware. Thank you
