### ISSUE TITLE
sunrise and sunset times

### ISSUE THREAD

**Issue by ShawnHarte** [OpenSprinkler/OpenSprinkler-Weather#3]
Sunrise and sunset are provided by weather.com api using astronomy sunrise/set.hour and sunrise/set.minute, not sure why the comments would say the info is not provided.

**Comment by salbahra** [comment]
The code correctly grabs the sunrise and sunset information when using Weather.com.

The comment you are mentioning is for Weather Underground which does not provide this data.

I believe this is just a misread of the code and I'm going to close this but if I'm missing something please let me know so we can reopen and investigate.

**Comment by ShawnHarte** [comment]
Weather underground DOES provide this data.  Under astronomy sunrise.hour sunrise.minute.  Weather.com and WU use the exact same data as weather.com owns WU.  Any method of acquiring data is fine, just the commented line provides false information.

**Comment by salbahra** [comment]
Is that a separate API call to Weather Underground? Because I do not see it in the reply for the current request.

**Comment by salbahra** [comment]
I believe you are referencing http://www.wunderground.com/weather/api/d/docs?d=data/astronomy

My comment is specifically for the current conditions call not having the data. You will notice I say this in the comment because Weather.com's API does return sunrise/sunset in the current conditions API call. No need to waste an API call when the script can calculate the sunrise/sunset, unless you are seeing some discrepancy?

**Comment by ShawnHarte** [comment]
For WU you could just add astronomy to the data in line with the others in a single request.  Weather.com uses the same API and data.  So both will have the same information available.

**Comment by salbahra** [comment]
Do you mind telling me how to add that to the current request?

**Comment by ShawnHarte** [comment]
The current method is much cleaner and I actually prefer it, I only had contention with saying something is not available when it is at no additional cost to API calls per day.

**Comment by salbahra** [comment]
Fair enough, I will update the comment (this issue caused me to realize the URL comment is also incorrect).

**Comment by ShawnHarte** [comment]
http://api.wunderground.com/api/" + weatherUndergroundKey +
		"/yesterday/conditions/astronomy/q/" + encodeURIComponent( location ) + ".json";

**Comment by salbahra** [comment]
I went ahead and switched to the method you suggested because it uses less processing/code on my end and therefore I find that a cleaner approach. The results seem very similar with maybe 1 minute difference for the most part.

Thanks again!
