### ISSUE TITLE
Trouble running this under Ubuntu 18.04

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#31]
Installed nodejs 11.15.0 and npm 6.7.0.  Installed os-weather-service.  Created systemd file, substituting correct directory on my system for WorkingDirectory.  

Get npm error, possibly because serve.js isn't in the weather directory but in weather/scripts???

I'm neither a Linux expert nor a JS expert, so I'm not sure what to try next.  

npm error  log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle os-weather-service@1.0.2~prestart: os-weather-service@1.0.2
6 silly lifecycle os-weather-service@1.0.2~prestart: no script for prestart, co$
7 info lifecycle os-weather-service@1.0.2~start: os-weather-service@1.0.2
8 verbose lifecycle os-weather-service@1.0.2~start: unsafe-perm in lifecycle tr$
9 verbose lifecycle os-weather-service@1.0.2~start: PATH: /usr/share/npm/bin/no$
10 verbose lifecycle os-weather-service@1.0.2~start: CWD: /home/roger/weather
11 silly lifecycle os-weather-service@1.0.2~start: Args: [ '-c', 'node js/serve$
12 silly lifecycle os-weather-service@1.0.2~start: Returned: code: 1  signal: n$
13 info lifecycle os-weather-service@1.0.2~start: Failed to exec start script
14 verbose stack Error: os-weather-service@1.0.2 start: `node js/server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/life$
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spaw$
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pro$
15 verbose pkgid os-weather-service@1.0.2
16 verbose cwd /home/roger/weather
17 error Linux 4.15.0-50-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error os-weather-service@1.0.2 start: `node js/server`
22 error Exit status 1
23 error Failed at the os-weather-service@1.0.2 start script 'node js/server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the os-weather-service p$
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node js/server

I have no idea what any of that means...

Rog

**Comment by salbahra** [comment]
Please run `npm run compile` to transpile the TS to JS first, then `npm start` will work fine.

Thanks!

**Comment by rmloeb** [comment]
THANK YOU!!!  I'm desperate to get OS working again with Zimmerman and I'm in over my head with both Linux and JS>  I very much appreciate your help!

Rog
