### ISSUE TITLE
Minor clarification for instructions

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#33]
In the weather-service instructions at step 8, it says to go to http://<your OSPi IP>:8080/su and specify “localhost:3000” as the new location for the weather service.

On some OS units, e.g., not OSPi, that should be port 80 rather than 8080.  If the weather-server is not on the same device as OS, e.g., not on OSPi, then the location should be "<weather-server IP>:3000"

**Comment by PeteBa** [comment]
Thanks for pointing this out. I have pushed a fix under #34 . Issue can be closed once PR merged.
