### ISSUE TITLE
Pushing data to weather-server from weewx

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#39]
If I use weewx to push WU data to weather-server, do I leave the weather provider out of the env file?

**Comment by rmloeb** [comment]
The rest of the question: if I'm pushing data from one of my Davis weatherstations, does that mean we're back to the "classic" Zimmerman calculation, i.e., previous days averages and today's precip?

**Comment by PeteBa** [comment]
If you add `PWS=WU` to the `.env` file then this will force the use of local data for Watering Level. Yes, the current PWS implementation uses the "classic" method i.e. mean temp/humidity from yesterday and precip from yesterday and today. Note that this may evolve going forward but that is the current implementation.

**Comment by rmloeb** [comment]
Thank you.
