### ISSUE TITLE
Push data from Davis to weather-service?

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#41]
I was in the process of implementing weewx to capture data from a Davis Vantage 2 to forward it to weather-service when I noticed that it may be possible to avoid that complication and push directly.  Davis sells both serial and USB "dataloggers" to connect the Vantage consoles to a PC and Weatherkink Windows software to display the console data.  There is also a DLL that
can push the data to WU.  Within that DLL there are two URLs: rtupdate.wunderground.com/weatherstation/updateweatherstation.php and weatherstation.wunderground.com/weatherstation/updateweatherstation.php.  I don't know what the first one does, but I understand the second one.  

Note: if I had the IP version of the datalogger, than I would use the suggested redirection approach, but the redirection doesn't readily work when the Davis software is running on a machine that supports other applications.

Since the weather-service captureWUStream() uses the same URL form as the second one in the Davis DLL, I thought I'd try redirecting the WU update calls by adding entries to the HOSTS file on the machine running Weatherlink.  I added entries that point to my instance of weather-server for wunderground.com, rtupdate.wunderground.com, and weatherstation.wunderground.com, rebooted, and restarted Davis Weatherlink.  When I ask Weatherlink to submit WU data, I get a "success" response.  However, I do not get any console logging from weather-service.  captureWUStream() has a console.log() statement in it.  Presumably, if the HOSTS file did its job, the data should have been submitted to weather-service, but the absence of a log record suggests otherwise.  

It's been a couple of decades since I used Wireshark, so before I submerge myself in relearning, I thought I'd first ask whether the approach even makes sense and whether my expectation of a log record from captureWUStream() overlooks some other logic in weather-server.

Suggestions?

**Comment by Derpthemeus** [comment]
Can you verify the hosts file was updated correctly by running `getent hosts weatherstation.wunderground.com`?

**Comment by rmloeb** [comment]
It's a Windows machine, so there is no "getent".  However, "ping weatherstation.wunderground.com" replies with the correct address of the weather-server.  nslookup, on the other hand, goes to the network DNS resolver and gets the actual wunderground IP.

**Comment by rmloeb** [comment]
OK.  The GET is being re-directed to weather-server, which is returning a 404, probably because the request is not formatted the way it's expected.

/weatherstation/updateweatherstation.php?action=updateraw&ID=KCOPARKE148&PASSWORD=********&dateutc=2019-05-22%2018:38:25&winddir=150&winddir_avg2m=149&windspeedmph=5&windgustmph=9&windgustmph_10m=9&windgustdir_10m=150&humidity=71&tempf=43.2&dewptf=34.4&rainin=0.00&solarradiation=610&dailyrainin=0.13&baromin=29.87&softwaretype=Wunderground%20v.1.15%20PWSDec%2027%202007 HTTP/1.1
User-Agent: wxex
Host: weatherstation.wunderground.com
Cache-Control: no-cache

**Comment by rmloeb** [comment]
Tried to update weather-service with a manual call from a browser, using the URL sample provided in the documentation, and got "Error: Request not found."

**Comment by PeteBa** [comment]
That error signals an unrecognised endpoint. (i.e. `/weatherstation/updateweatherstation.php` is not enabled).

Can you check that the `.env` file has `PWS=WU`. And that the service is listening i.e. `OpenSprinkler Weather Service now listening for local weather stream` is sent to the console log.

It might be worth adding the following at line 36 in server.ts (you will need to recompile):
```
		console.log( "Unrecognised request: %s", JSON.stringify( req ) );
```

Am I right in saying that this was working for you but has now stopped working ? Is there something that you have changed recently ?

**Comment by rmloeb** [comment]
YES!!!

I did not previously have this working, but I do now.  My error.  I did not have PWS=WU in .env.   I had WEATHER-PROVIDER=WU.

This is much better than attempting to use weewx as a relay.

Thanks to all of you.  I am now back to using local data for the Zimmerman calculation and I am very grateful.  

Incidentally, I have been tracking local weather as reported by my PWS, DarkSky, and OWM.  OWM's "forecast" is beyond absurd and varies dramatically from DarkSky (in a bad way).  DarkSky is close to local actual, usually off by a 2-3 degrees (high).

**Comment by PeteBa** [comment]
@rmloeb great to hear.

Any chance you could jot down a few notes on how you configured the DNS redirect and post to this thread ? I can then add to the instructions so others can benefit as well.

**Comment by rmloeb** [comment]
**How to push Davis Vantage weather data directly to a local instance of weather-service** (if you have a serial or USB Davis weather logger; if you have the WeatherLinkIP version, see the instructions for using a RaspberryPi Zero to redirect weather data to local weather-service):

Davis Weatherlink software has an optional DLL, WUiWlink_1.dll (dated 4/26/17), which is designed to push observation data from the Davis Vantage weather consoles to WeatherUnderground's now obsolete interface.  That feature can be used to push data to a local instance of weather-service, which will, in turn, be accessed by OpenSprinkler as data for the Zimmerman water level calculation.  To install that module, see the directions at http://www.davisinstruments.com/resource/send-weather-data-weather-underground-weatherlink-software/

To make this work, modify the HOSTS file on the Windows machine running Weatherlink by adding these three lines:
<local weather-service IP>    wunderground.com
<local weather-service IP>    rtupdate.wunderground.com
<local weather-service IP>    weatherstation.wunderground.com

This will redirect all wunderground.com calls from this specific machine to the local weather-server. so be aware of that should you attempt to make any other calls to wunderground.com.

[Note: you must be running in administrator mode to make this change.  The HOSTS file is in C:/Windows/System32/drivers/etc.  The easiest way to do this is to open a Command Prompt in Admin mode, navigate to C:/Windows/System32/drivers/etc, then execute "notepad.exe hosts", add the three entries, save, exit, and close the command window.]

In Weatherlink you should see "Wunderground settings" in the File menu.  You can ignore the StationID and Password settings (or just enter a single blank character).  Set the Update Interval to 60 minutes, which should be more than sufficient for the purpose of the Zimmerman water level calculation.

Actual readings from your PWS should now be flowing to weather-service.  Make sure you have Zimmerman selected in OpenSprinkler and set the parameters appropriately for your situation.

If you want to test this, stop weather-service on whatever machine it is running on, open a terminal window, change to the weather directory (in your home directory), and run weather-service directly with "npm start."  Every time that Weatherlink pushes data, you will see that data logged to the console by weather-server.  When you are satisfied that it's working as expected, stop weather-service with Ctrl-C, then restart it with "systemctl start weather.service."  Close the terminal session.  (This is easiest to observe if you first change the Update Interval in Davis Weatherlink to something less than 60 minutes.  Don't forget to change it back.)

**Comment by PeteBa** [comment]
@rmloeb That's great ! Many thanks.

**Comment by rmloeb** [comment]
And many thanks to you for your patience and assistance!  Couldn't have done it without you.
