### ISSUE TITLE
Water Level Calculation

### ISSUE THREAD

**Issue by rmloeb** [OpenSprinkler/OpenSprinkler-Weather#44]
I'm questioning the water level calculation being made by the local weather server and need some assistance checking my own math.  (I also realize that Rick Zimmerman's formula isn't always interpreted in the same way, so my application of the formula may also be incorrect.)

I'm using data reported by my local PWS.  The weather server is returning a water level of 95% based on the previous day's average temperature of 53.2 degrees, previous day's average humidity of 47.37%, and 0 rain.  I have the configuration set for a base average temperature of 60 degrees, base precipitation expectation of 0.1" of rain, and base average humidity of 40%.  These are weighted temp=75%, humidity=100%, precipitation=50%.  

Based on my calculations, that should result in a water level of 82%, not 95%.

Humidity: Average humidity for the previous day above (30%) 40% (my parameter) is subtracted from weather adjustment, below 40% is added to it.
     (40-47.37) = -7.37%

Temperature: +4% for each degree F above (70) 60 (my parameter); -4% for each degree below 60.
     60-53.2 = 6.8; 6.8 * - 4% = -27.2%

Precipitation: -2% for each hundredth of an inch of precip (above base parameter value!); by inference, +2% for each hundredth of an inch of precip below base parameter value.
   .1 - 0 = .1; 10 * +2% = 20%

Weighted sum: ((-7.37 * 100%) + (-27.2 * 75%) + (20 * 50%)/100) = -17.77%

Water Level: 100% -17.77% = 82%

Where did I go wrong?

**Comment by PeteBa** [comment]
Don't know as those numbers work on my dev box:
```
&scale=82&rd=-1&tz=24&sunrise=339&sunset=1215&eip=2130706433&rawData={"h":47.4,"p":0,"t":53.2,"raining":0}
```

Can you post the two log messages i.e. the request and the response ?

**Comment by rmloeb** [comment]
I did not save the data and I restarted weather.service, so it doesn't have the previous day's readings and is using current weather.  I will test again when it has a day's worth of data to work with.

**Comment by rmloeb** [comment]
Found the error is my calculations.  I had the weights for humidity and precipitation reversed when I entered them in my model.  My error, again.

Z calculations for past several calls correspond to the results of my Zimmerman model.
