### ISSUE TITLE
Normalise icons into a  set of standard conditions

### ISSUE THREAD

**Issue by PeteBa** [OpenSprinkler/OpenSprinkler-Weather#46]
I think we need to translate weather provider specific `icons` into a normalised set of `conditions` that we then report onward to App. We could use MDI Icons for App. I found the mappings below from Home Assistant showing OWM/DarkSky/MDI:

| Condition | MDI Icons | DarkSky Icons | OWM Icons | OWM Condition |
| --- | --- | --- | --- | --- |
| Clear | 'weather-sunny'<br>'weather-night' | 'clear-day'<br>'clear-night' | 01d, 01n | Clear (All) - 8XX |
| Rain | 'weather-rainy' | 'rain' | 09d, 09n | Drizzle (All) - 3XX<br>Rain (Shower) - 520-522, 530 |
| Pour | 'weather-pouring' |  | 10d, 10n | Rain (Heavy) - 500-504 |
| Snow | 'weather-snowy' | 'snow' | 13d, 13n | Snow (Snow) - 600-602 |
| Sleet | 'weather-snowy-rainy' | 'sleet' | 13d, 13n | Rain (Freezing) - 511<br>Snow (Sleet) - 611-613<br>Snow (Shower) - 620-622<br>Snow (Rain) - 615-616 |
| Wind | 'weather-windy' | 'wind' |  | Wind (Windy) - 905, 951-957 |
| Gale | 'weather-windy-variant' |  |  | Wind (Gale) - 958-960 |
| Fog | 'weather-fog' | 'fog' | 50d, 50n | Atmosphere (Mist) - 701<br>Atmosphere (Fog) - 741 |
| Cloud | 'weather-cloudy' | 'cloudy' | 04d, 04n | Cloudy (Overcast) - 803-804 |
| Part Cloud | 'weather-partlycloudy' | 'partly-cloudy-day'<br>'partly-cloudy-night' | 02d, 02n<br>03d, 03n | Cloudy (Scattered) - 801-802 |
| Hail | 'weather-hail' | 'hail' |  | Extreme (Hail) - 906 |
| Thunderstorm | 'weather-lightning-rainy' | 'thunderstorm' | 11d, 11n | Thunderstorm (All) - 2XX |
| Hurrucane | 'weather-hurricane' | 'tornado' |  | Wind (Storm) - 900-902, 961-962 |

Unmapped OWM
711 - Smoke, 721 - Haze, 731 - Dust, 751 - Sand, 761 - Dust, 762 - Ash, 771 - Squall

Alternative to MDI could be owfont [here](https://websygen.github.io/owfont/)

_Originally posted by @PeteBa in https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/38_

**Comment by rmloeb** [comment]
Do any of the providers have a condition for hail?  Is there an icon for hail?  In my part of the U.S., that's the most destructive spring/summer weather.  Sometimes the U.S. Weather Service is able to forecast hail and there's a local weatherman who has an excellent crystal ball.

**Comment by PeteBa** [comment]
Looks like now standardised on OWM icons. Closing.
