### ISSUE TITLE
Clean up logic in adjustment option handling

### ISSUE THREAD

**Issue by PeteBa** [OpenSprinkler/OpenSprinkler-Weather#60]
getWateringData() logic around adjustment option handling could be clearer.

PeteBa replied:
>I don't like the logic in this area. It is too convoluted with nested ifs and > METHOD.MANUAL conditions that all feels a bit hard to decipher. Not one for this PR but I'll open an issue for consideration at a latter point.

_Originally posted by @PeteBa in https://github.com/OpenSprinkler/OpenSprinkler-Weather/pull/58_

**Comment by Derpthemeus** [comment]
I'm planning to clean up this part of the code by separating https://github.com/Derpthemeus/OpenSprinkler-Weather/commit/d4b427b1b2c6049060ac26047c39bb6549e9f02d from #51 and putting it in its own PR

**Comment by Derpthemeus** [comment]
Resolved in 0281a835e256d3de789175a1be0ad0a1e5ba741a
