### ISSUE TITLE
OWM only uses 3 hour forecast

### ISSUE THREAD

**Issue by tekhedd** [OpenSprinkler/OpenSprinkler-Weather#8]
getOWMWeatherData() only uses the average temp/rainfall/etc for the first 3 hour window. I'm guessing it should actually average the first (thinking.. 24/3=) 8 bins to get a 24 hour forecast. 

Yes there are suggestions to use the "time until next watering" but I'm thinking it is more important to have consistent behavior vs the old wunderground API, which looks like it delivered a 24 hour average. Plus it's simple because the data is already there, just  needs a short loop.

I really don't have time for this but at the moment the OWM code is essentially useless, more so if you water (as I do) an hour before sunrise...so... I guess what I'm saying is that if *nobody* has time to do this change, I suppose I could start pulling all the dev bits.

**Comment by tekhedd** [comment]
(Also note that the WU function pulls the current temperature, not the daily average, which means that 

  1) The watering base temperature should probably be set to the expected temp at time of watering, not the average daily temperature, and 
  2) OWM should probably collect only the first bin / current temp

**Comment by salbahra** [comment]
Thank you so much for this suggestion! I can hopefully get this done this week. I’ll keep you posted and update as soon as I can.

**Comment by tekhedd** [comment]
Awesome! 

I also wonder: shouldn't the temperature for both WU and OWM be a 24 hour average? If the forum threads are any indication, the Zimmerman algorithm is supposed to be configured with the average daily temp, not the current. Possibly this is some of the reason people need to decrease its contribution so much! Which 24 hours? Doesn't matter: previous, next, as long as it's an average it's better than a single sample, right? Probably the WU data does not include average temp? Just thinking out loud. 

It doesn't look like a tough change--sorry I didn't bring a PR...I'll look into doing some dev asap, I have an 8266 module sitting here looking unused staring at me accusingly

**Comment by salbahra** [comment]
@tekhedd I have a commit containing the average logic as suggested: https://github.com/OpenSprinkler/OpenSprinkler-Weather/commit/5d7b5651a57a8099a92a445c78097b41a895d7cc

Let me know what you think before I deploy these.

**Comment by tekhedd** [comment]
Oh, just realized I added my comment on the commit. :o Sorry. Quoted here for reference:

The 5-day forecast API returns 3-hour interval chunks. Therefore, maxCount should be 8 so that the temperature is a 24-hour average and not weighted towards the next 6-hour period. Yes? This also applies to humidity and to a much lesser extent wind and precipitation. [edit] Or maybe this is intentional? THat would work for precip but not for temp...

In fact, temp/humidity calculation should probably fail entirely if data.list.length < 8, for the same reason. It looks like this function succeeds/fails atomically, so I would simply fail the whole function if data.list.length < 8, and set maxCount to 8.

**Comment by salbahra** [comment]
Just checked and it seems I am using the daily forecast instead of hourly now so this should be fixed now. The loop we have now is just to generate the forecast data for the app. I am going to close this for now but please let me know if there is still an issue.
