### ISSUE TITLE
DarkSky no longer available to new users

### ISSUE THREAD

**Issue by kpfleming** [OpenSprinkler/OpenSprinkler-Weather#93]
https://blog.darksky.net/

Apple has purchased DarkSky, and as a result the API signup service has been shut down. Users with existing keys can use the API until the end of 2021, but are now subject to Apple's privacy policy.

**Comment by kpfleming** [comment]
This is going to result in a very difficult situation for OpenSprinkler-Weather users; WU is no longer available, DarkSky isn't available to new users (and will stop working for existing users in 20 months), and OWM's data availability and quality are very poor.

**Comment by rayshobby** [comment]
Unless if you are running weather server on your own computer, the opensprinkler weather server uses a DS key that we have paid for. Users are never asked to create or provide their own key.

**Comment by kpfleming** [comment]
That was indeed my point; there is no practical way for a user to run their own weather server now.

**Comment by rayshobby** [comment]
You mean advanced user / developer? Typical users are not going to set up their own weather server. 
Look, you don't need to use DS. WU is still supported by firmware 2.1.9, and we have some users to who it as of now:
https://openthings.freshdesk.com/support/solutions/articles/5000017485

**Comment by kpfleming** [comment]
Yes, advanced users, those to want to run all three parts of OS on their own systems (firmware, weather server, UI website). There are some of us weirdos out there, as evidenced by the occasional forum threads where people run into issues setting up their own systems.

I can't use WU, as I don't have a key for it and can't get one, so at the moment I can't run my own weather server. This is in no way your fault of course, you are only providing a connection to third-party services, but the lack of friendly third-party services means that most new users who want to run their own weather server won't be able to do that.

**Comment by rayshobby** [comment]
I am not sure if you read the article link I posted -- you CAN still get a WU key even if you haven't acquired one in the past, or even if you don't own a PWS device yourself. The article describes how anyone can get a WU key.

**Comment by kpfleming** [comment]
You are correct, I apologize that I had not followed the link, I assumed it was still the long-existing article on how to use WU. I'll read it later today and give it a try.
